Задание 3
PakhomovIA/TSA-142 pull request #11
Opened 2024-06-04 22:15 UTC by PakhomovIA

2024-06-04 22:15 UTC, PakhomovIA commented
[Отчёт3.docx](https://github.com/user-attachments/files/15570955/3.docx)

2024-06-06 10:41 UTC, BalakinaEP requested changes

2024-06-06 10:41 UTC, BalakinaEP commented on 3Task.cpp
> +    }
В отдельную функцию

2024-06-10 07:22 UTC, BalakinaEP requested changes

2024-06-10 07:22 UTC, BalakinaEP commented on 3Task.cpp
> +bool isNatural(int num);
const

2024-06-10 07:22 UTC, BalakinaEP commented on 3Task.cpp
> +bool isInteger(float num);
const

2024-06-10 07:22 UTC, BalakinaEP commented on 3Task.cpp
> +float calculateAverage(int num1, int num2);
const

2024-06-10 07:22 UTC, BalakinaEP commented on 3Task.cpp
> +    bool isNatural(int num1);
Что это?

2024-06-10 08:12 UTC, BalakinaEP requested changes
не исправили

2024-06-11 09:41 UTC, BalakinaEP requested changes

2024-06-11 09:41 UTC, BalakinaEP commented on 3Task.cpp
> +    cin >> num1;
не проверили ввод

2024-06-11 09:41 UTC, BalakinaEP commented on 3Task.cpp
> +    bool isNatural(const int num1);
что это? Зачем это здесь?

2024-06-11 09:41 UTC, BalakinaEP commented on 3Task.cpp
> +    bool isNatural(const int num2);
аналогично

2024-06-13 08:08 UTC, BalakinaEP requested changes
не исправили

2024-06-13 09:45 UTC, merged