Задание 7
PakhomovIA/TSA-142 pull request #12
Opened 2024-06-09 21:37 UTC by PakhomovIA

2024-06-10 07:26 UTC, BalakinaEP requested changes

2024-06-10 07:26 UTC, BalakinaEP commented on 7.cpp
> +    printMatrix(second_task_arr, (n + (n / 2)), m);
неверно выделяете память. Четная строка имеет нечетный индекс

2024-06-10 07:26 UTC, BalakinaEP commented on 7.cpp
> +        if (i % 2 == 0) {
аналогично

2024-06-10 07:26 UTC, BalakinaEP commented on 7.cpp
> +    alloc(&newArr, n + (n / 2), m);
неверно выделена пямять

2024-06-13 08:11 UTC, BalakinaEP requested changes
не приложено задание

2024-06-13 08:20 UTC, PakhomovIA commented
![image](https://github.com/PakhomovIA/TSA-142/assets/160127085/d9058e49-3484-412b-a94b-485ffa29ae98)

2024-06-13 08:49 UTC, BalakinaEP requested changes

2024-06-13 08:49 UTC, BalakinaEP commented on 7.cpp
> +    }
через switch

2024-06-13 08:49 UTC, BalakinaEP commented on 7.cpp
> +    return 0;
делаем все задания последовательно, а не одно из

не изменяем исходный массив.

2024-06-13 09:46 UTC, BalakinaEP requested changes
неверно работает вставка, не тот массив печатаете в конце

![image](https://github.com/PakhomovIA/TSA-142/assets/114657505/d1729fd3-9a36-464c-9a93-e48e17605db6)

2024-06-14 07:22 UTC, BalakinaEP approved these changes

2024-06-14 08:17 UTC, closed without merging